services:
  portfolio:
    container_name: portfolio
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=America/New_York
    ports:
      - "10082:80"
    networks:
      - public
    restart: unless-stopped

networks:
  public:
    external: true